[package]
name = "digitaljs-wasm-worker"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
path = "srcRust/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2"
